@extends('layouts.app')

@section('content')
<div class="space-y-6"><div><h1 class="text-2xl font-bold">Buat Barang Keluar</h1><p class="text-sm text-slate-400">Simpan sebagai draft, stok baru berkurang saat posting.</p></div>
<form method="POST" action="{{ route('goods-issues.store') }}" class="space-y-6">@csrf
<div class="grid gap-4 rounded-xl border border-slate-800 bg-slate-900/70 p-4 md:grid-cols-3">
<label class="text-sm">Tanggal<input type="date" name="issue_date" value="{{ old('issue_date', now()->toDateString()) }}" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"></label>
<label class="text-sm">Lokasi Asal<select name="source_location_id" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Pilih</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('source_location_id')==$location->id)>{{ $location->code }} - {{ $location->name }}</option>@endforeach</select></label>
<label class="text-sm">PIC Penyerah<select name="pic_user_id" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Pilih</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('pic_user_id')==$user->id)>{{ $user->name }}</option>@endforeach</select></label>
<label class="text-sm">Jenis Penerima<select name="recipient_type" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="external">External</option><option value="user">User</option><option value="location">Lokasi</option></select></label>
<label class="text-sm">User Penerima<select name="recipient_user_id" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Opsional</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></label>
<label class="text-sm">Lokasi Tujuan<select name="target_location_id" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Opsional</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->code }} - {{ $location->name }}</option>@endforeach</select></label>
<label class="text-sm">Nama Penerima<input name="recipient_name" value="{{ old('recipient_name') }}" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"></label>
<label class="text-sm">Departemen<input name="recipient_department" value="{{ old('recipient_department') }}" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"></label>
<label class="text-sm">Telepon<input name="recipient_phone" value="{{ old('recipient_phone') }}" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"></label>
<label class="text-sm md:col-span-3">Catatan<textarea name="remarks" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2">{{ old('remarks') }}</textarea></label>
</div>
<div class="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><h2 class="mb-3 font-semibold">Detail Item</h2><div class="space-y-3">@for($i=0;$i<5;$i++)<div class="grid gap-3 md:grid-cols-5"><select name="items[{{ $i }}][item_id]" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Pilih Barang</option>@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->sku }} - {{ $item->name }}</option>@endforeach</select><input type="number" min="1" name="items[{{ $i }}][qty]" placeholder="Qty" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"><input name="items[{{ $i }}][serial_no]" placeholder="Serial" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"><select name="items[{{ $i }}][condition_status]" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="good">Good</option><option value="new">New</option><option value="used">Used</option><option value="repaired">Repaired</option><option value="damaged">Damaged</option></select><input name="items[{{ $i }}][notes]" placeholder="Catatan" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"></div>@endfor</div></div>
@if($errors->any())<div class="rounded border border-red-800 bg-red-950/40 p-4 text-sm text-red-200"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="flex gap-2"><button class="rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Simpan Draft</button><a href="{{ route('goods-issues.index') }}" class="rounded border border-slate-700 px-4 py-2 text-sm">Batal</a></div>
</form></div>
@endsection
