@extends('layouts.app')

@section('content')
<div class="space-y-6"><div><h1 class="text-2xl font-bold">Input Barang Tarikan</h1><p class="text-sm text-slate-400">Draft tidak mengubah stok. Stok bertambah hanya untuk final action return_to_stock saat posting.</p></div>
<form method="POST" action="{{ route('goods-returns.store') }}" enctype="multipart/form-data" class="space-y-6">@csrf
<div class="grid gap-4 rounded-xl border border-slate-800 bg-slate-900/70 p-4 md:grid-cols-3">
<label class="text-sm">Tanggal Penarikan<input type="date" name="return_date" value="{{ old('return_date', now()->toDateString()) }}" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"></label>
<label class="text-sm">Asal Barang<select name="origin_type" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="location">Lokasi</option><option value="user">User</option></select></label>
<label class="text-sm">Gudang Tujuan<select name="warehouse_location_id" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Pilih</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->code }} - {{ $location->name }}</option>@endforeach</select></label>
<label class="text-sm">User Asal<select name="origin_user_id" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Opsional</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></label>
<label class="text-sm">Lokasi Asal<select name="origin_location_id" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Opsional</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->code }} - {{ $location->name }}</option>@endforeach</select></label>
<label class="text-sm">PIC Asal<input name="origin_pic_name" value="{{ old('origin_pic_name') }}" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"></label>
<label class="text-sm">Kontak PIC<input name="origin_pic_phone" value="{{ old('origin_pic_phone') }}" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2"></label>
<label class="text-sm md:col-span-2">Alasan Penarikan<textarea name="return_reason" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2">{{ old('return_reason') }}</textarea></label>
<label class="text-sm md:col-span-3">Catatan<textarea name="remarks" class="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2">{{ old('remarks') }}</textarea></label>
</div>
<div class="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><h2 class="mb-3 font-semibold">Detail Barang</h2><div class="space-y-3">@for($i=0;$i<5;$i++)<div class="grid gap-3 md:grid-cols-6"><select name="items[{{ $i }}][item_id]" class="rounded border border-slate-700 bg-slate-950 px-3 py-2 md:col-span-2"><option value="">Pilih Barang</option>@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->sku }} - {{ $item->name }}</option>@endforeach</select><input type="number" min="1" name="items[{{ $i }}][qty]" placeholder="Qty" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"><input name="items[{{ $i }}][serial_no]" placeholder="Serial" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"><select name="items[{{ $i }}][condition_status]" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="layak_pakai">Layak Pakai</option><option value="rusak_ringan">Rusak Ringan</option><option value="rusak_berat">Rusak Berat</option><option value="scrap">Scrap</option></select><select name="items[{{ $i }}][final_action]" class="rounded border border-slate-700 bg-slate-950 px-3 py-2"><option value="return_to_stock">Kembali ke Stok</option><option value="repair">Repair</option><option value="scrap">Scrap</option><option value="dispose">Dispose</option></select><input type="file" multiple name="items[{{ $i }}][photos][]" class="rounded border border-slate-700 bg-slate-950 px-3 py-2 md:col-span-2"><input name="items[{{ $i }}][notes]" placeholder="Catatan" class="rounded border border-slate-700 bg-slate-950 px-3 py-2 md:col-span-4"></div>@endfor</div></div>
@if($errors->any())<div class="rounded border border-red-800 bg-red-950/40 p-4 text-sm text-red-200"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="flex gap-2"><button class="rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Simpan Draft</button><a href="{{ route('goods-returns.index') }}" class="rounded border border-slate-700 px-4 py-2 text-sm">Batal</a></div>
</form></div>
@endsection
